import type { Metadata } from "next";
import { Heebo } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const inter = Heebo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}  relative`}>
        <main className="relative">
          <div>
            <Navbar />
          </div>

          <div className="container">{children}</div>
        </main>
      </body>
    </html>
  );
}
